1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
127: eth0@if128: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:14:14:06 brd ff:ff:ff:ff:ff:ff link-netnsid 0
129: eth1@if130: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether aa:c1:ab:d1:28:83 brd ff:ff:ff:ff:ff:ff link-netnsid 1
134: eth2@if133: <BROADCAST,MULTICAST,UP> mtu 9500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether aa:c1:ab:35:a2:0f brd ff:ff:ff:ff:ff:ff link-netnsid 0
