1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
113: eth0@if114: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:14:14:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
116: eth1@if115: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default 
    link/ether aa:c1:ab:b4:c2:83 brd ff:ff:ff:ff:ff:ff link-netnsid 0
118: eth2@if117: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default 
    link/ether aa:c1:ab:50:b5:4f brd ff:ff:ff:ff:ff:ff link-netnsid 0
