1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
107: eth0@if108: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
110: eth1@if109: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default 
    link/ether aa:c1:ab:9e:a5:d5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
112: eth2@if111: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default 
    link/ether aa:c1:ab:dc:a7:ed brd ff:ff:ff:ff:ff:ff link-netnsid 0
